"""Puertos: interfaces que el dominio y los casos de uso necesitan.

La infraestructura las implementa. La dependencia apunta hacia adentro.
"""
from __future__ import annotations

from datetime import date
from typing import Protocol, Sequence

from dominio.configuracion import Parametros
from dominio.modelos import Instrumento, Posicion, Precio


class RepositorioInstrumentos(Protocol):
    def listar(self, incluir_eliminados: bool = False) -> list[Instrumento]: ...
    def obtener(self, isin: str) -> Instrumento | None: ...
    def guardar(self, instrumento: Instrumento, usuario: str) -> None: ...
    def eliminar(self, isin: str, usuario: str, motivo: str) -> None: ...
    def reactivar(self, isin: str, usuario: str) -> None: ...


class RepositorioPosiciones(Protocol):
    def listar(self, incluir_eliminadas: bool = False) -> list[Posicion]: ...
    def obtener(self, id_posicion: int) -> Posicion | None: ...
    def guardar(self, posicion: Posicion, usuario: str) -> int: ...
    def eliminar(self, id_posicion: int, usuario: str, motivo: str) -> None: ...
    def reactivar(self, id_posicion: int, usuario: str) -> None: ...


class RepositorioPrecios(Protocol):
    def por_instrumento(self, isin: str) -> list[Precio]: ...
    def todos(self) -> dict[str, list[Precio]]: ...


class RepositorioParametros(Protocol):
    def leer(self) -> Parametros: ...
    def escribir(self, cambios: dict[str, str], usuario: str) -> None: ...


class RepositorioBitacora(Protocol):
    def registrar(self, accion: str, usuario: str, **datos: object) -> None: ...
